apiVersion: v2
name: wine-emulator
description: A Helm chart for Wine Emulator Platform with Counter-Strike 1.6 gaming support
type: application
version: 1.0.0
appVersion: "10.0"
keywords:
  - wine
  - gaming
  - emulator
  - counter-strike
  - vnc
  - kubernetes
home: https://github.com/kozuchowskihubert/azure-virt-kube
sources:
  - https://github.com/kozuchowskihubert/azure-virt-kube
maintainers:
  - name: haos
    email: hubert.kozuchowski@gmail.com
  - x64
  - translation
maintainers:
  - name: Wine Emulator Team
    email: team@example.com
