apiVersion: v1
kind: Service
metadata:
  name: wine-emulator
  namespace: wine-emulator
  labels:
    app: wine-emulator
spec:
  type: LoadBalancer
  selector:
    app: wine-emulator
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    protocol: TCP
  - name: vnc
    port: 5900
    targetPort: 5900
    protocol: TCP
