apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "wine-emulator.fullname" . }}-config
  labels:
    {{- include "wine-emulator.labels" . | nindent 4 }}
data:
  {{- toYaml .Values.configMap.data | nindent 2 }}
